theme: jekyll-theme-minimal
baseurl: "/home"
title: "Neurophysio Oerlikon"
description: "Physiotherapy for neurodegenerative diseases"

# domain: my-site.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
# url: https://my-site.github.io  # the base hostname and protocol for your site, e.g. http://example.com